import React from 'react';
import {
  Feather,
  Book,
  BookOpen,
  Lock,
  Unlock,
  Search,
  Calendar,
  Settings,
  Plus,
  X,
  ChevronLeft,
  ChevronRight,
  Heart,
  Moon,
  Sun,
  Camera,
  Download,
  Trash2,
  Edit2,
  Check,
  User,
  Mail,
  Eye,
  EyeOff,
  Pin,
  Flame,
  Fingerprint,
  Key,
  Delete,
  Shield,
  ShieldCheck,
  Trophy,
  Filter,
  Clock,
  Bell,
  Sparkles,
  Bookmark,
  Upload,
  Info,
  AlertTriangle,
  FileText,
  Smile,
  Frown,
  Waves,
  Zap,
  HeartHandshake,
  Lightbulb,
  Send,
  MessageSquare,
  Palette,
  Copy,
  AlertCircle,
  HelpCircle,
} from 'lucide-react';

/**
 * Professional Lucide SVG icons mapping for Antarang design system.
 */
const LUCIDE_MAP = {
  quill: Feather,
  book: Book,
  'book-open': BookOpen,
  lock: Lock,
  unlock: Unlock,
  search: Search,
  calendar: Calendar,
  settings: Settings,
  plus: Plus,
  close: X,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'heart-outline': Heart,
  moon: Moon,
  sun: Sun,
  camera: Camera,
  download: Download,
  trash: Trash2,
  edit: Edit2,
  check: Check,
  user: User,
  mail: Mail,
  eye: Eye,
  'eye-off': EyeOff,
  pin: Pin,
  streak: Flame,
  flame: Flame,
  fingerprint: Fingerprint,
  key: Key,
  backspace: Delete,
  shield: Shield,
  'shield-check': ShieldCheck,
  trophy: Trophy,
  filter: Filter,
  clock: Clock,
  bell: Bell,
  sparkles: Sparkles,
  bookmark: Bookmark,
  upload: Upload,
  info: Info,
  'alert-triangle': AlertTriangle,
  'alert-circle': AlertCircle,
  'file-text': FileText,
  happy: Smile,
  sad: Frown,
  calm: Waves,
  anxious: Zap,
  grateful: HeartHandshake,
  loved: Heart,
  angry: Flame,
  thoughtful: Lightbulb,
  send: Send,
  'message-square': MessageSquare,
  palette: Palette,
  copy: Copy,
};

export default function Icon({ name, size = 24, className = '', strokeWidth = 1.8, ...props }) {
  const IconComponent = LUCIDE_MAP[name] || HelpCircle;
  return (
    <IconComponent
      size={size}
      strokeWidth={strokeWidth}
      className={className}
      {...props}
    />
  );
}

export { Icon };
